### ISSUE TITLE
Prepare a detailed review of washopenresearch data package

### ISSUE THREAD

**Issue by larnsce** [openwashdata/washopenresearch#1]
Hi @mianzg. I am starting a complete review of the package. I will work on a new `dev` branch and will incorporate some changes as I go along. Here I will document the changes, so that you can also use the suggestions for the time that you start working on the `openwashdata` R package.

**Comment by larnsce** [comment]
I have reviewed the `README.rmd` and `data_processing.R`. Will continue with the rest at a later point.

## README.rmd

- thanks for including the wrapping at 72, please include that in README.rmd template for `openwashdata` R package

- I included four additional options in the `knitr::opts_chunk$set()`. These help with figure display.

- badges: add the R-CMD-check workflow from `usethis::use_github_action_check_standard()`. This will also add the badge.

- I like the wordcloud, but how where is the code for it? Any visualisation in the package should be together with the code for it. At the beginning of the README, keep the code as echo=false, but then show the code further down in the Example section. If you use the wordcloud, then it would also need a short description about what is displayed there. I would prefer a plot from further below that highlights an interesting aspect of the data (e.g. Top 10 countries of first author)

- I edited numbers to inline code

- I like the scrollable variable table a lot.

- A Methods section is missing that describes the data collection process. See more details further below. 

### Example

1. What are the top 10 countries(or regions) the first authors from in the *Journal of Water, Sanitation and Hygiene for Development*?

- This variable needs to be country or region. It should not be both. If we have the country, then we can enhance the data with an addditional region column. 

- This variable also needs a lot more further clean up. There are university departments in there, countries with different spellings, NAs. Please use `mutate(case_when())` combination to clean up this variable.

2. What are the top choices of keywords in WASH Dev?

That's a nice analysis. 

## data_processing.R

Overall: the two resources need to be able to be merged seemlessly. If you apply `bind_rows(washdev, uncnewsletter)`, all vector types need to match, all categories need to be named consistently, etc.

It's the same data from two sources.

### washdev:

- line 11 to line 30: there is more work to do here. 
- consider cleaning up the author names, so that counts will actually yield the correct result

### uncnewsletter:

- what's the first colum `...1`?
- `is_supp`: in `washdev` this is a logical type, here it is character type. Select one and be consistent.
- `num_supp`: in `washdev` you have NA for no supplement, here it is a 0. Select one and be consistent.
- `supp_file_type`: there are strings that say "excel & word". Extract this and make it a list-column (e.g. `c`(excel, word))
- `has_das`: fix inconsistency between the two dataframes
- `das_type`: different categories between this and `washdev`. fix to be equal to `washdev`.

## dictionary.csv

- make this "country" and clean up the variable, and then use ISO3 codes and the R `countrycodes` package to enrich the data with a region (same for uncnewsletter)

https://github.com/openwashdata/washopenresearch/blob/052dfabd7c727b1815cc79c5829c841d028a3f4b/data-raw/dictionary.csv#L16

- same here, make it "country" and clean up the variable complete (same for uncnewsletter)

https://github.com/openwashdata/washopenresearch/blob/052dfabd7c727b1815cc79c5829c841d028a3f4b/data-raw/dictionary.csv#L21

- it says: todo here:

https://github.com/openwashdata/washopenresearch/blob/052dfabd7c727b1815cc79c5829c841d028a3f4b/data-raw/dictionary.csv#L26

## washdev.csv

Where is the code that has produced the "washdev.csv"?

https://github.com/openwashdata/washopenresearch/blob/main/data-raw/washdev.csv

The code also needs to be in the package, even if it is a Python script. A new "Methods" section in the README.rmd needs to describe your workflow. Is the workflow reproducible? How can someone else (me) run the script to get the same results. 

## unc-article-url-manual-collection.csv

In the Methods section in the README.rmd include a short paragraph that describes how this data was collected. 

https://github.com/openwashdata/washopenresearch/blob/main/data-raw/unc-article-url-manual-collection.csv

## CITATION.cff

- You can leave this up to me. Once you have worked throgh the review, let me know in #2

## examples.Rmd

- Remove his for now. The remaining tasks for the package have priority.

**Comment by mianzg** [comment]
# README.rmd
1. For the download table and scrollable view of dictionary, I opened an issue to track needed elements for readme here: https://github.com/openwashdata-dev/openwashdata/issues/18
2. Maybe I'm wrong. Our previous data packages also followed that an example visualization at the top just to showcase with a `echo=False` code chunk, sometimes even a screenshot. Would you like to change this from now on?

- [x] decide on the 1st figure
- [x] add on a short description about the 1st figure

**Comment by mianzg** [comment]
# Data collection documentation

- [x] Convert jupyter notebook into python scripts
- [x] attach python scripts in `inst/python`: https://stackoverflow.com/questions/60150956/attaching-python-script-while-building-r-package
- [x] write up collection method for two datasets

**Comment by mianzg** [comment]
# data_processing.R
## General 

- [x] @larnsce There are a few variables that one dataset has and the other not and I did not exclude them because it might be interesting to analyze. We can discuss if we what to keep:

`washdev` only: "volume" and "issue" numbers. we did not record for `uncnewsletter` because they are less important to reduce more manual collection work
`uncnewsletter` only: 
- issue_url: it refers to the url of the newsletter archive
- url_source: it refers to the publish website e.g. mdpi, we can add this to `washdev` but it's just the same value
- citations: number of citations, i can't scrape this information for washdev

**SOLUTION**: Keep everything, make sure overlap variables are expressed in the same data type and format.

## uncnewsletter:

- [x] changes shown in rda but not the script, check the local files:  column `...1`, `is_supp`, `has_das`, 

- [x] num_supp: in washdev you have NA for no supplement, here it is a 0. Select one and be consistent.

- [x] supp_file_type: there are strings that say "excel & word". Extract this and make it a list-column (e.g. c(excel, word))

- [x] das_type: different categories between this and washdev. fix to be equal to washdev. @larnsce `uncnewsletter` has two corner types, "no datasets were generated during the study" and "not shareable", would you like to merge these two into `NA`? FYI, `NA` in washdev means that there is no das (i.e. before implementing das) whereas the new 2 types in `uncnewsletter` are explicitly written in their das.

## washdev

- [ ] check `supp_file_type` is misc and `num_supp` is 2, the scraping python code gets it to be misc.

**Comment by mianzg** [comment]
b76f8bb9ecd436c19ad00fc6dfe5bb0c7b3f97ff 
cleaned up first author affiliation region, and see if applying this to the rest

**Comment by larnsce** [comment]
Great work, @mianzg. I see everything implemented besides one comment:

- for all country variables, include another variable that identifies the country by ISO3 code (e.g. `first_author_affiliation_country_iso3`)

I agree with your comment above. Keep the first figure without code, you have the code further down.

I have opened a PR and made some edits in the README.Rmd. It currently does not render.

https://github.com/openwashdata/washopenresearch/pull/5

**Comment by larnsce** [comment]
I have opened a PR and made some edits in the README.Rmd. It currently does not render.
